[build]
builder = "nixpacks"

[deploy]
startCommand = "python orcamail-server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
# force redeploy Sat Jun  6 02:06:01 PM EDT 2026
